import { FACILITY_CODES, FACILITY_LABELS, REASON_LABELS, type AdminVenueProfile, type VenueProfileFacilityCode, type VenueProfileItemState, type VenueProfileUploadIntent } from "../../domain/venue-profile";
import { readInventoryHeaderLayout } from "../../presentation/inventory-layout";
import { getVenueProfileAttemptStore } from "../../services/venue-profile-attempt-store";
import { getVenueProfileDataSource, getVenueProfileMediaCapability, type ChosenVenueProfileImage, type VenueProfileMutationAttempt } from "../../services/venue-profile";

type DatasetEvent = { currentTarget?: { dataset?: Record<string, unknown> } };
type InputEvent = { detail?: { value?: unknown } };
type PageError = { code?: string };
type RefreshOrigin = "page" | "image" | "description";
type ImageView = { id: string; cover: boolean; state: VenueProfileItemState; url: string; alt: string; stateLabel: string; reasonLabel: string; actionsEnabled: boolean };
const MAX_IMAGES = 8;
const GROUPS: readonly { title: string; codes: readonly VenueProfileFacilityCode[] }[] = [
  { title: "基础设施", codes: ["PARKING", "TOILET", "CHANGING_ROOM", "SHOWER", "LOCKERS"] }, { title: "补给服务", codes: ["DRINKING_WATER", "BEVERAGE_SALES", "EQUIPMENT_RENTAL"] }, { title: "观赛与安全", codes: ["REST_AREA", "FIRST_AID", "AED"] }, { title: "场地环境", codes: ["INDOOR", "OUTDOOR", "COVERED", "LIGHTING"] }, { title: "草皮类型", codes: ["ARTIFICIAL_TURF", "NATURAL_GRASS"] },
];
const key = (kind: string) => `venue-profile-${kind}-${Date.now()}-${Math.round(Math.random() * 1e9)}`;
const codePoints = (value: string) => Array.from(value);
const errorCode = (caught: unknown) => (caught as PageError)?.code ?? "";
const pending = (state: VenueProfileItemState) => state === "UPLOADING" || state === "REVIEWING" || state === "PENDING_MANUAL";
const sameFacilities = (left: readonly VenueProfileFacilityCode[], right: readonly VenueProfileFacilityCode[]) => left.length === right.length && left.every((code, index) => code === right[index]);

Page({
  data: {
    venueId: "", venueName: "", mode: "loading", status: "正在读取场馆资料", statusDetail: "", tone: "loading", pageRefreshError: "",
    profile: null as AdminVenueProfile | null, description: "", descriptionCount: 0, facilities: [] as VenueProfileFacilityCode[], facilityGroups: [] as unknown[], images: [] as ImageView[], imageCount: 0, maxImages: MAX_IMAGES,
    descriptionDirty: false, facilitiesDirty: false, descriptionEditable: false, facilitiesEditable: false, imageActionsEnabled: false, imagePending: false, descriptionPending: false, descriptionStateLabel: "", descriptionReasonLabel: "", descriptionSubmitEnabled: false, descriptionActionLabel: "", facilitySaveEnabled: false, facilitySaveBlockedReason: "",
    imageRefreshError: "", descriptionRefreshError: "", imageActionError: "", descriptionActionError: "", facilitySaveError: "", imageRefreshBusy: false, descriptionRefreshBusy: false, descriptionSubmitBusy: false, facilitySaveBusy: false, operationBusy: false, writeBusy: false, busyItemId: "", unknownScope: "",
    headerTopPx: 0, headerRowHeightPx: 44, headerRightInsetPx: 0,
  },
  requestSequence: 0, refreshGeneration: 0, activeRefreshGeneration: 0, activeRefreshOrigin: undefined as RefreshOrigin | undefined, disposed: false, mutationInFlight: false, refreshInFlight: undefined as Promise<void> | undefined, imageRefreshTimer: undefined as ReturnType<typeof setTimeout> | undefined, descriptionRefreshTimer: undefined as ReturnType<typeof setTimeout> | undefined,

  async onLoad(options: Record<string, string | undefined> = {}) {
    this.disposed = false; const layout = readInventoryHeaderLayout(); const venueId = options.venue_id ?? "";
    this.setData({ venueId, headerTopPx: layout.topPx, headerRowHeightPx: layout.rowHeightPx, headerRightInsetPx: layout.rightInsetPx });
    if (!venueId) { this.failRead("场馆信息无效，请返回重试"); return; }
    try { await getVenueProfileDataSource().login(); await this.loadProfile("page", false); } catch (caught) { this.handleReadError(caught, "page", true); }
  },
  onUnload() { this.disposed = true; this.requestSequence += 1; this.activeRefreshGeneration = 0; this.refreshInFlight = undefined; if (this.imageRefreshTimer) clearTimeout(this.imageRefreshTimer); if (this.descriptionRefreshTimer) clearTimeout(this.descriptionRefreshTimer); },
  onShow() {},
  async loadProfile(origin: RefreshOrigin, initial = false) {
    if (this.refreshInFlight) return this.refreshInFlight;
    const sequence = ++this.requestSequence; const generation = ++this.refreshGeneration; this.activeRefreshGeneration = generation; this.activeRefreshOrigin = origin;
    if (origin === "image") this.setData({ imageRefreshBusy: true, imageRefreshError: "" });
    if (origin === "description") this.setData({ descriptionRefreshBusy: true, descriptionRefreshError: "" });
    const request = (async () => {
      try { const profile = await getVenueProfileDataSource().get(this.data.venueId); if (!this.disposed && sequence === this.requestSequence) { this.applyProfile(profile); const attempt = getVenueProfileAttemptStore()?.load(); if (attempt?.venueId === this.data.venueId) { if (attempt.kind === "save" && attempt.scope === "description" && !this.data.descriptionDirty) this.setData({ description: attempt.body.description, descriptionCount: codePoints(attempt.body.description).length, descriptionDirty: true }); if (attempt.kind === "save" && attempt.scope === "facilities" && !this.data.facilitiesDirty) this.setData({ facilities: [...attempt.body.facilities], facilityGroups: this.groupsFor(attempt.body.facilities), facilitiesDirty: true }); } this.syncUnknownScope(); } }
      catch (caught) { if (this.disposed || sequence !== this.requestSequence) return; this.handleReadError(caught, origin, initial); throw caught; }
      finally { if (this.activeRefreshGeneration !== generation) return; if (!this.disposed && origin === "image") this.setData({ imageRefreshBusy: false }); if (!this.disposed && origin === "description") this.setData({ descriptionRefreshBusy: false }); this.activeRefreshOrigin = undefined; this.refreshInFlight = undefined; }
    })();
    this.refreshInFlight = request; return request;
  },
  applyProfile(profile: AdminVenueProfile) {
    const revision = profile.currentRevision; const description = this.data.descriptionDirty ? this.data.description : revision.description; const facilities = this.data.facilitiesDirty ? this.data.facilities : [...revision.facilities];
    const safePublished = (revision.summaryState === "READY" || revision.summaryState === "PUBLISHED") && revision.images.every((image) => image.state === "APPROVED"); const publishedByOrder = safePublished ? new Map(profile.published.images.map((image) => [image.sortOrder, image.url])) : new Map<number, string>();
    const images = [...revision.images].sort((a, b) => a.sortOrder - b.sortOrder).map((image) => ({ id: image.id, cover: image.role === "COVER", state: image.state, url: publishedByOrder.get(image.sortOrder) ?? "", alt: image.alt, stateLabel: this.itemStateLabel(image.state), reasonLabel: image.reasonCode ? REASON_LABELS[image.reasonCode] : "", actionsEnabled: !pending(image.state) }));
    const imagePending = revision.images.some((image) => pending(image.state)); const descriptionPending = revision.descriptionState === "REVIEWING" || revision.descriptionState === "PENDING_MANUAL"; const facilitySaveBlockedReason = imagePending ? "图片正在审核，审核结束后可保存设施" : descriptionPending ? "场馆介绍正在审核，审核结束后可保存设施" : "";
    const loaded = true;
    const descriptionActionLabel = this.data.descriptionDirty ? revision.descriptionState === "REJECTED" ? "提交修改" : "提交场馆介绍" : revision.descriptionState === "REJECTED" ? "重新审核介绍" : "";
    this.setData({ profile, venueName: profile.venue.name, mode: "ready", description, descriptionCount: codePoints(description).length, facilities, facilityGroups: this.groupsFor(facilities), images, imageCount: images.length, descriptionEditable: loaded, facilitiesEditable: loaded, imageActionsEnabled: loaded, imagePending, descriptionPending, descriptionStateLabel: this.itemStateLabel(revision.descriptionState), descriptionReasonLabel: revision.descriptionReasonCode ? REASON_LABELS[revision.descriptionReasonCode] : "", descriptionSubmitEnabled: this.data.descriptionDirty && !descriptionPending && !this.data.descriptionSubmitBusy, descriptionActionLabel, facilitySaveEnabled: this.data.facilitiesDirty && !facilitySaveBlockedReason && !this.data.facilitySaveBusy, facilitySaveBlockedReason, imageRefreshError: "", descriptionRefreshError: "", pageRefreshError: "", operationBusy: false, busyItemId: "" });
  },
  itemStateLabel(state: VenueProfileItemState) { return ({ UPLOADING: "上传中", REVIEWING: "审核中", APPROVED: "已通过", REJECTED: "未通过", PENDING_MANUAL: "人工审核" } as const)[state]; },
  invalidateReads() { this.requestSequence += 1; if (!this.disposed && this.activeRefreshOrigin === "image") this.setData({ imageRefreshBusy: false }); if (!this.disposed && this.activeRefreshOrigin === "description") this.setData({ descriptionRefreshBusy: false }); this.activeRefreshGeneration = 0; this.activeRefreshOrigin = undefined; this.refreshInFlight = undefined; },
  async withMutation<T>(work: () => Promise<T>, replay = false) { if (this.disposed || this.mutationInFlight || (this.data.unknownScope && !replay)) return undefined; this.mutationInFlight = true; this.invalidateReads(); this.setData({ writeBusy: true }); try { return await work(); } finally { this.mutationInFlight = false; if (!this.disposed) this.setData({ writeBusy: false }); } },
  disableForPermission() { this.setData({ mode: "permission-error", status: "当前账号无权管理该场馆", statusDetail: "请联系场馆管理员确认权限", tone: "error", descriptionEditable: false, facilitiesEditable: false, imageActionsEnabled: false, descriptionSubmitEnabled: false, facilitySaveEnabled: false, operationBusy: false, writeBusy: false, imageRefreshBusy: false, descriptionRefreshBusy: false, descriptionSubmitBusy: false, facilitySaveBusy: false, busyItemId: "" }); },
  attemptScope(attempt: VenueProfileMutationAttempt) { return attempt.kind === "save" ? attempt.scope : attempt.kind === "retry" && attempt.itemId === this.data.profile?.currentRevision.id ? "description" : "image"; },
  syncUnknownScope(afterFailure = false) { if (this.disposed || (this.mutationInFlight && !afterFailure)) return; const attempt = getVenueProfileAttemptStore()?.load(); this.setData({ unknownScope: attempt?.venueId === this.data.venueId ? this.attemptScope(attempt) : "" }); },
  groupsFor(selected: readonly VenueProfileFacilityCode[]) { return GROUPS.map((group) => ({ title: group.title, items: group.codes.map((code) => ({ code, label: FACILITY_LABELS[code], selected: selected.includes(code) })) })); },
  onDescriptionInput(event: InputEvent) { if (!this.data.descriptionEditable) return; const value = typeof event.detail?.value === "string" ? event.detail.value : ""; const description = codePoints(value).slice(0, 300).join(""); this.setData({ description, descriptionCount: codePoints(description).length, descriptionDirty: true, descriptionActionError: "", descriptionSubmitEnabled: !this.data.descriptionPending && !this.data.descriptionSubmitBusy, descriptionActionLabel: this.data.profile?.currentRevision.descriptionState === "REJECTED" ? "提交修改" : "提交场馆介绍" }); },
  onToggleFacility(event: DatasetEvent) { const code = event.currentTarget?.dataset?.facilityCode; if (!this.data.facilitiesEditable || typeof code !== "string" || !FACILITY_CODES.includes(code as VenueProfileFacilityCode)) return; const typed = code as VenueProfileFacilityCode; const facilities = this.data.facilities.includes(typed) ? this.data.facilities.filter((item) => item !== typed) : [...this.data.facilities, typed]; this.setData({ facilities, facilityGroups: this.groupsFor(facilities), facilitiesDirty: true, facilitySaveError: "", facilitySaveEnabled: !this.data.facilitySaveBlockedReason && !this.data.facilitySaveBusy }); },
  async onSubmitDescription() { if (!this.data.profile || this.data.unknownScope || !this.data.descriptionDirty || this.data.descriptionPending || this.data.descriptionSubmitBusy) return; const attempt = { kind: "save" as const, scope: "description" as const, venueId: this.data.venueId, body: { expectedFacilityVersion: this.data.profile.facilityVersion, expectedRevisionVersion: this.data.profile.revisionVersion, description: this.data.description, facilities: this.data.profile.currentRevision.facilities }, idempotencyKey: key("description") }; return this.runScopedSave(attempt); },
  async onRetryDescription() { if (!this.data.profile || this.data.unknownScope || this.data.descriptionDirty || this.data.profile.currentRevision.descriptionState !== "REJECTED" || this.data.descriptionSubmitBusy) return; const attempt = { kind: "retry" as const, venueId: this.data.venueId, itemId: this.data.profile.currentRevision.id, expectedRevisionVersion: this.data.profile.revisionVersion, idempotencyKey: key("description-retry") }; return this.runDescriptionRetry(attempt); },
  async onSaveFacilities() { if (!this.data.profile || this.data.unknownScope || !this.data.facilitiesDirty || this.data.facilitySaveBlockedReason || this.data.facilitySaveBusy) return; const attempt = { kind: "save" as const, scope: "facilities" as const, venueId: this.data.venueId, body: { expectedFacilityVersion: this.data.profile.facilityVersion, expectedRevisionVersion: this.data.profile.revisionVersion, description: this.data.profile.currentRevision.description, facilities: this.data.facilities }, idempotencyKey: key("facilities") }; return this.runScopedSave(attempt); },
  async runScopedSave(attempt: Extract<VenueProfileMutationAttempt, { kind: "save" }>, replay = false) { return this.withMutation(async () => {
    const store = getVenueProfileAttemptStore();
    try { const stable = (store?.begin(attempt) ?? attempt) as typeof attempt; const submittedDescription = stable.body.description; const submittedFacilities = [...stable.body.facilities]; this.setData(attempt.scope === "description" ? { descriptionSubmitBusy: true, descriptionSubmitEnabled: false, descriptionActionError: "" } : { facilitySaveBusy: true, facilitySaveEnabled: false, facilitySaveError: "" }); const profile = await getVenueProfileDataSource().save(stable); if (this.disposed) return; store?.clear(); this.invalidateReads(); const changedDuringSave = attempt.scope === "description" ? this.data.description !== submittedDescription : !sameFacilities(this.data.facilities, submittedFacilities); this.setData(attempt.scope === "description" ? { descriptionDirty: changedDuringSave, descriptionSubmitBusy: false, unknownScope: "" } : { facilitiesDirty: changedDuringSave, facilitySaveBusy: false, unknownScope: "" }); this.applyProfile(profile); if (attempt.scope === "description") this.scheduleRefresh("description"); }
    catch (caught) { if (this.disposed) return; this.setData(attempt.scope === "description" ? { descriptionSubmitBusy: false, descriptionSubmitEnabled: this.data.descriptionDirty && !this.data.descriptionPending } : { facilitySaveBusy: false, facilitySaveEnabled: this.data.facilitiesDirty && !this.data.facilitySaveBlockedReason }); this.handleMutationError(caught, attempt.scope); }
  }, replay); },
  async runDescriptionRetry(attempt: Extract<VenueProfileMutationAttempt, { kind: "retry" }>, replay = false) { return this.withMutation(async () => { const store = getVenueProfileAttemptStore(); try { const stable = store?.begin(attempt) ?? attempt; this.setData({ descriptionSubmitBusy: true, descriptionActionError: "" }); const profile = await getVenueProfileDataSource().retryModeration(stable as typeof attempt); if (this.disposed) return; store?.clear(); this.invalidateReads(); this.setData({ descriptionSubmitBusy: false, unknownScope: "" }); this.applyProfile(profile); this.scheduleRefresh("description"); } catch (caught) { if (!this.disposed) { this.setData({ descriptionSubmitBusy: false }); this.handleMutationError(caught, "description"); } } }, replay); },
  scheduleRefresh(region: "image" | "description") { if (this.disposed) return; const timer = region === "image" ? "imageRefreshTimer" : "descriptionRefreshTimer"; if (this[timer]) clearTimeout(this[timer]); this[timer] = setTimeout(() => { this[timer] = undefined; if (!this.disposed) void this.loadProfile(region).catch(() => undefined); }, 5000); },
  async onRefreshImageStatus() { if (!this.data.imagePending && !this.data.imageRefreshError) return; return this.loadProfile("image").catch(() => undefined); },
  async onRefreshDescriptionStatus() { if (!this.data.descriptionPending && !this.data.descriptionRefreshError) return; return this.loadProfile("description").catch(() => undefined); },
  async onPullDownRefresh() { try { await this.loadProfile("page"); } catch { /* page error is rendered above */ } finally { wx.stopPullDownRefresh(); } },
  async onChooseImage() { const profile = this.data.profile; if (this.data.unknownScope || !this.data.imageActionsEnabled || !profile || this.data.imageCount >= MAX_IMAGES) return; return this.withMutation(async () => { try { this.setData({ operationBusy: true, imageActionError: "" }); const image = await getVenueProfileMediaCapability().chooseImage(); const attempt = { kind: "uploadIntent" as const, venueId: this.data.venueId, body: { expectedRevisionVersion: profile.revisionVersion, filename: image.filename, mimeType: image.mimeType, byteSize: image.byteSize }, idempotencyKey: key("upload") }; const stable = getVenueProfileAttemptStore()?.begin(attempt) as typeof attempt | undefined ?? attempt; const intent = await getVenueProfileDataSource().createUploadIntent(stable); await this.finishUpload(stable, intent, image); } catch (caught) { if (!this.disposed) this.handleMutationError(caught, "image"); } }); },
  onRetryUpload() { return getVenueProfileAttemptStore()?.load()?.kind === "uploadIntent" ? this.onRetryUnknown() : this.onChooseImage(); },
  async finishUpload(attempt: Extract<VenueProfileMutationAttempt, { kind: "uploadIntent" }>, intent: VenueProfileUploadIntent, selected?: ChosenVenueProfileImage) { const store = getVenueProfileAttemptStore(); store?.clear(); store?.begin(attempt); const image = selected ?? await getVenueProfileMediaCapability().chooseImage(); if (image.filename !== attempt.body.filename || image.mimeType !== attempt.body.mimeType || image.byteSize !== attempt.body.byteSize) throw Object.assign(new Error("MEDIA_FILE_MISMATCH"), { code: "MEDIA_FILE_MISMATCH" }); await getVenueProfileMediaCapability().upload(intent.signedPutUrl, image.bytes, intent.requiredHeaders); store?.clear(); const complete = { kind: "complete" as const, venueId: this.data.venueId, imageId: intent.imageId, expectedRevisionVersion: attempt.body.expectedRevisionVersion + 1, idempotencyKey: key("complete") }; const stable = store?.begin(complete) as typeof complete | undefined ?? complete; const profile = await getVenueProfileDataSource().completeUpload(stable); if (this.disposed) return; store?.clear(); this.invalidateReads(); this.setData({ unknownScope: "" }); this.applyProfile(profile); this.scheduleRefresh("image"); },
  imageId(event: DatasetEvent) { const imageId = event.currentTarget?.dataset?.imageId; return !this.data.unknownScope && this.data.imageActionsEnabled && typeof imageId === "string" && this.data.images.find((image) => image.id === imageId)?.actionsEnabled && this.data.busyItemId !== imageId ? imageId : ""; },
  async onSetCover(event: DatasetEvent) { const id = this.imageId(event); if (id) return this.runImage(id, "cover", (a) => getVenueProfileDataSource().setCover(a as Extract<VenueProfileMutationAttempt, { kind: "cover" }>)); },
  async onRemoveImage(event: DatasetEvent) { const id = this.imageId(event); if (id && !this.data.images.find((image) => image.id === id)?.cover) return this.runImage(id, "delete", (a) => getVenueProfileDataSource().deleteImage(a as Extract<VenueProfileMutationAttempt, { kind: "delete" }>)); },
  async onReorderImage(event: DatasetEvent) { const id = this.imageId(event); const direction = Number(event.currentTarget?.dataset?.direction); if (!id || !this.data.profile || !Number.isInteger(direction)) return; const ids = this.data.images.map((image) => image.id); const from = ids.indexOf(id); const to = Math.max(1, Math.min(ids.length - 1, from + direction)); if (from < 1 || from === to) return; [ids[from], ids[to]] = [ids[to], ids[from]]; const attempt = { kind: "reorder" as const, venueId: this.data.venueId, imageIds: ids, expectedRevisionVersion: this.data.profile.revisionVersion, idempotencyKey: key("reorder") }; return this.runImageAttempt(attempt, (a) => getVenueProfileDataSource().reorderImages(a as Extract<VenueProfileMutationAttempt, { kind: "reorder" }>), id); },
  async onRetryModeration(event: DatasetEvent) { const itemId = event.currentTarget?.dataset?.itemId; if (this.data.unknownScope || !this.data.imageActionsEnabled || typeof itemId !== "string" || !this.data.profile) return; const attempt = { kind: "retry" as const, venueId: this.data.venueId, itemId, expectedRevisionVersion: this.data.profile.revisionVersion, idempotencyKey: key("retry") }; return this.runImageAttempt(attempt, (a) => getVenueProfileDataSource().retryModeration(a as Extract<VenueProfileMutationAttempt, { kind: "retry" }>), itemId); },
  async runImage(id: string, kind: "cover" | "delete", call: (attempt: VenueProfileMutationAttempt) => Promise<AdminVenueProfile>) { if (!this.data.profile) return; return this.runImageAttempt({ kind, venueId: this.data.venueId, imageId: id, expectedRevisionVersion: this.data.profile.revisionVersion, idempotencyKey: key(kind) } as VenueProfileMutationAttempt, call, id); },
  async runImageAttempt(attempt: VenueProfileMutationAttempt, call: (attempt: VenueProfileMutationAttempt) => Promise<AdminVenueProfile>, busyItemId = "", replay = false) { return this.withMutation(async () => { try { const stable = getVenueProfileAttemptStore()?.begin(attempt) ?? attempt; this.setData({ operationBusy: true, busyItemId, imageActionError: "" }); const profile = await call(stable); if (this.disposed) return; getVenueProfileAttemptStore()?.clear(); this.invalidateReads(); this.setData({ unknownScope: "" }); this.applyProfile(profile); if (attempt.kind === "retry" || attempt.kind === "complete") this.scheduleRefresh("image"); } catch (caught) { if (!this.disposed) this.handleMutationError(caught, "image"); } }, replay); },
  async onRetryUnknown() { const attempt = getVenueProfileAttemptStore()?.load(); if (!attempt || attempt.venueId !== this.data.venueId) { this.syncUnknownScope(); return this.loadProfile("page").catch(() => undefined); } if (attempt.kind === "save") return this.runScopedSave(attempt, true); if (attempt.kind === "retry" && this.attemptScope(attempt) === "description") return this.runDescriptionRetry(attempt, true); if (attempt.kind === "uploadIntent") return this.withMutation(async () => { try { this.setData({ operationBusy: true, imageActionError: "" }); const intent = await getVenueProfileDataSource().createUploadIntent(attempt); await this.finishUpload(attempt, intent); if (!this.disposed) this.setData({ unknownScope: "" }); } catch (caught) { if (!this.disposed) this.handleMutationError(caught, "image"); } }, true); const source = getVenueProfileDataSource(); const calls = { complete: source.completeUpload, delete: source.deleteImage, cover: source.setCover, reorder: source.reorderImages, retry: source.retryModeration }; return this.runImageAttempt(attempt, (a) => (calls[a.kind as keyof typeof calls] as (value: never) => Promise<AdminVenueProfile>)(a as never), "", true); },
  async onReload() { try { await this.loadProfile("page", true); } catch { /* rendered by loadProfile */ } },
  handleReadError(caught: unknown, origin: RefreshOrigin, initial: boolean) { const code = errorCode(caught); if (code === "VENUE_PROFILE_FORBIDDEN" || code === "AUTH_REQUIRED") { this.disableForPermission(); return; } if (initial || !this.data.profile) { this.failRead("场馆资料加载失败，请重试"); return; } if (origin === "image") this.setData({ imageRefreshError: "图片状态刷新失败，请重试" }); else if (origin === "description") this.setData({ descriptionRefreshError: "介绍状态刷新失败，请重试" }); else this.setData({ pageRefreshError: "资料刷新失败，请重试", tone: "error", statusDetail: "请检查网络后下拉刷新" }); },
  handleMutationError(caught: unknown, scope: "image" | "description" | "facilities") { const code = errorCode(caught); if (code === "VENUE_PROFILE_FORBIDDEN" || code === "AUTH_REQUIRED") { this.disableForPermission(); return; } if (code === "VENUE_PROFILE_VERSION_CONFLICT") { this.setData({ operationBusy: false, busyItemId: "" }); void this.loadProfile("page").catch(() => undefined); return; }
    if (code === "VENUE_PROFILE_RESULT_UNKNOWN") { this.setData(scope === "description" ? { descriptionActionError: "提交结果未知，请核对后重试", unknownScope: "description" } : scope === "facilities" ? { facilitySaveError: "保存结果未知，请核对后重试", unknownScope: "facilities" } : { imageActionError: "图片操作结果未知，请核对后重试", unknownScope: "image" }); this.syncUnknownScope(true); return; }
    this.setData({ operationBusy: false, busyItemId: "", ...(scope === "description" ? { descriptionActionError: "介绍提交失败，请重试" } : scope === "facilities" ? { facilitySaveError: "设施保存失败，请重试" } : { imageActionError: code === "MEDIA_FILE_MISMATCH" ? "请选择与原上传一致的图片" : "图片操作失败，请重试" }) }); this.syncUnknownScope(true);
  },
  failRead(message: string) { this.setData({ mode: "load-error", status: message, statusDetail: "上一版公开资料不受影响", tone: "error", profile: null }); },
  onNavigateWorkbench(event: DatasetEvent) { const target = event.currentTarget?.dataset?.target; const suffix = `?venue_id=${encodeURIComponent(this.data.venueId)}`; if (target === "profile") { void wx.redirectTo({ url: `/pages/venue-profile/index${suffix}` }); return; } if (target === "pitches") void wx.navigateTo({ url: `/pages/venue-pitch-setup/index${suffix}` }); if (target === "inventory") void wx.navigateTo({ url: `/pages/venue-inventory/index${suffix}` }); },
  onBack() { if (!this.data.descriptionDirty && !this.data.facilitiesDirty) { void wx.redirectTo({ url: "/pages/venue-access/index" }); return; } wx.showModal({ title: "放弃未保存修改？", content: "场馆介绍或设施尚未保存。", confirmText: "放弃", success: ({ confirm }) => { if (confirm) void wx.redirectTo({ url: "/pages/venue-access/index" }); } }); },
});
