(function exposePlatformOnboardingFixture(scope) {
  const fixture = {
    meta: {
      environmentLabel: "Development-only Fixture",
      truthLabel: "视觉预览，不会提交或修改生产数据",
      reviewerName: "平台审核员",
      reviewerRole: "ONBOARDING_REVIEWER",
    },
    previewCases: {
      "login": { screen: "login", selectedId: "app-claim-pending" },
      "pending": { screen: "review", selectedId: "app-claim-pending" },
      "approved": { screen: "review", selectedId: "app-create-approved" },
      "rejected": { screen: "review", selectedId: "app-claim-rejected" },
      "expired-evidence-link": {
        screen: "review",
        selectedId: "app-create-pending",
        expiredEvidenceIds: ["evidence-create-license"],
        initialWarning: "营业执照或主体证明预览链接已过期；重新获取只更新本地 Fixture。",
      },
      "decision-error": {
        screen: "review",
        selectedId: "app-claim-pending",
        decisionShouldFail: true,
        initialError: "提交决定失败：申请状态可能已变化。刷新详情后再重试。",
      },
    },
    applications: [
      {
        id: "app-claim-pending",
        number: "ONB-20260817-0038",
        kind: "CLAIM",
        status: "SUBMITTED",
        submittedAt: "2026-08-17 09:42",
        relativeTime: "18 分钟前",
        applicant: { name: "周启航", phone: "138 **** 7621" },
        targetVenue: {
          id: "venue-hongkou-park",
          name: "虹口足球公园",
          district: "上海市虹口区",
          address: "广中路 444 号",
        },
        duplicateRisk: {
          title: "重复风险提示",
          detail: "系统发现同名场馆 1 条，请核对目标场馆与授权材料。",
          match: "虹口足球公园 · 目标场馆一致",
        },
        suggestedReason: "申请人与现有场馆信息一致，授权材料完整。",
        evidence: [
          {
            id: "evidence-claim-authorization",
            label: "经营或管理授权证明",
            filename: "虹口足球公园授权书.pdf",
            format: "PDF",
            size: "1.8 MB",
            receivedAt: "2026-08-17 09:38",
          },
          {
            id: "evidence-claim-exterior",
            label: "场馆外部现场证明",
            filename: "虹口足球公园外部.jpg",
            format: "JPG",
            size: "2.4 MB",
            receivedAt: "2026-08-17 09:39",
          },
        ],
        decision: null,
      },
      {
        id: "app-create-pending",
        number: "ONB-20260817-0037",
        kind: "CREATE",
        status: "SUBMITTED",
        submittedAt: "2026-08-17 08:18",
        relativeTime: "1 小时前",
        applicant: { name: "吴晨", phone: "139 **** 1068" },
        proposedVenue: {
          name: "杨浦滨江足球中心",
          district: "上海市杨浦区",
          address: "安浦路 615 号滨江运动园 2 号入口",
          location: "121.5386, 31.2631",
        },
        duplicateRisk: {
          title: "距离核验提示",
          detail: "距离最近的现有场馆 438 米，未触发 300 米重复阈值。",
          match: "最近：杨浦体育活动中心 · 438 米",
        },
        suggestedReason: "主体、地址与授权材料核验一致。",
        evidence: [
          {
            id: "evidence-create-license",
            label: "营业执照或主体证明",
            filename: "启航体育营业执照.pdf",
            format: "PDF",
            size: "1.2 MB",
            receivedAt: "2026-08-17 08:11",
          },
          {
            id: "evidence-create-authorization",
            label: "产权、租赁或管理授权证明",
            filename: "滨江运动园租赁协议.pdf",
            format: "PDF",
            size: "3.6 MB",
            receivedAt: "2026-08-17 08:12",
          },
          {
            id: "evidence-create-exterior",
            label: "场馆外部现场证明",
            filename: "滨江足球中心外部.jpg",
            format: "JPG",
            size: "2.8 MB",
            receivedAt: "2026-08-17 08:13",
          },
          {
            id: "evidence-create-interior",
            label: "场馆内部现场证明",
            filename: "滨江足球中心内部.jpg",
            format: "JPG",
            size: "4.1 MB",
            receivedAt: "2026-08-17 08:14",
          },
        ],
        decision: null,
      },
      {
        id: "app-create-approved",
        number: "ONB-20260816-0029",
        kind: "CREATE",
        status: "APPROVED",
        submittedAt: "2026-08-16 15:24",
        relativeTime: "昨天",
        applicant: { name: "林晓峰", phone: "136 **** 5582" },
        proposedVenue: {
          name: "浦东张江足球公园",
          district: "上海市浦东新区",
          address: "科苑路 88 号张江体育公园东区",
          location: "121.5941, 31.2047",
        },
        duplicateRisk: {
          title: "距离核验提示",
          detail: "最近的现有场馆距离 1.2 公里，未发现重复记录。",
          match: "未发现需阻断的重复场馆",
        },
        suggestedReason: "",
        evidence: [
          { id: "evidence-approved-license", label: "营业执照或主体证明", filename: "张江体育营业执照.pdf", format: "PDF", size: "1.4 MB", receivedAt: "2026-08-16 15:18" },
          { id: "evidence-approved-auth", label: "产权、租赁或管理授权证明", filename: "场地运营授权.pdf", format: "PDF", size: "2.1 MB", receivedAt: "2026-08-16 15:19" },
          { id: "evidence-approved-exterior", label: "场馆外部现场证明", filename: "张江足球公园外部.jpg", format: "JPG", size: "2.6 MB", receivedAt: "2026-08-16 15:20" },
          { id: "evidence-approved-interior", label: "场馆内部现场证明", filename: "张江足球公园内部.jpg", format: "JPG", size: "3.7 MB", receivedAt: "2026-08-16 15:21" },
        ],
        decision: {
          outcome: "APPROVED",
          reason: "主体、地址和授权材料核验一致，同意创建未公开场馆。",
          reviewer: "平台审核员",
          reviewedAt: "2026-08-17 10:18",
        },
      },
      {
        id: "app-claim-rejected",
        number: "ONB-20260816-0026",
        kind: "CLAIM",
        status: "REJECTED",
        submittedAt: "2026-08-16 11:03",
        relativeTime: "昨天",
        applicant: { name: "陈嘉", phone: "137 **** 2239" },
        targetVenue: {
          id: "venue-jingan-sports",
          name: "静安运动中心",
          district: "上海市静安区",
          address: "康定路 151 号",
        },
        duplicateRisk: {
          title: "重复风险提示",
          detail: "目标场馆唯一，申请人主体与授权文件抬头不一致。",
          match: "静安运动中心 · 目标场馆一致",
        },
        suggestedReason: "",
        evidence: [
          { id: "evidence-rejected-auth", label: "经营或管理授权证明", filename: "管理授权说明.pdf", format: "PDF", size: "740 KB", receivedAt: "2026-08-16 10:58" },
          { id: "evidence-rejected-exterior", label: "场馆外部现场证明", filename: "静安运动中心外部.jpg", format: "JPG", size: "2.2 MB", receivedAt: "2026-08-16 10:59" },
        ],
        decision: {
          outcome: "REJECTED",
          reason: "授权书未包含场馆完整名称，且签章页缺失。",
          reviewer: "平台审核员",
          reviewedAt: "2026-08-16 16:42",
        },
      },
    ],
  };

  scope.PLATFORM_ONBOARDING_FIXTURE = Object.freeze(fixture);
})(globalThis);
