"""venue inventory

Revision ID: 0001
Revises:
Create Date: 2026-07-24 14:32:56.572896

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price_advantage_text", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("business_hours_text", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("parking_text", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("refund_policy_text", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_venues_latitude"),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_venues_name_nonempty"),
        sa.CheckConstraint("length(trim(slug)) > 0", name="ck_venues_slug_nonempty"),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_venues_longitude"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "uq_one_active_primary_venue",
        "venues",
        [sa.literal_column("(true)")],
        unique=True,
        postgresql_where=sa.text("is_primary AND is_active"),
    )
    op.create_table(
        "pitches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "pitch_type", sa.Enum("FIVE_A_SIDE", "SEVEN_A_SIDE", name="pitch_type"), nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("length(trim(code)) > 0", name="ck_pitches_code_nonempty"),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_pitches_name_nonempty"),
        sa.CheckConstraint("sort_order >= 0", name="ck_pitches_sort_order"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "code", name="uq_pitches_venue_code"),
    )
    op.create_index("ix_pitches_venue_id", "pitches", ["venue_id"], unique=False)
    op.create_table(
        "venue_facilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column(
            "code",
            sa.Enum("LIGHTING", "CHANGING_ROOM", "DRINKING_WATER", "PARKING", name="facility_code"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_venue_facilities_name_nonempty"),
        sa.CheckConstraint("sort_order >= 0", name="ck_venue_facilities_sort_order"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "code", name="uq_venue_facilities_venue_code"),
    )
    op.create_index("ix_venue_facilities_venue_id", "venue_facilities", ["venue_id"], unique=False)
    op.create_table(
        "venue_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("venue_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("alt", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("COVER", "GALLERY", name="image_role"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("url ~ '^https://'", name="ck_venue_images_https_url"),
        sa.CheckConstraint("length(trim(alt)) > 0", name="ck_venue_images_alt_nonempty"),
        sa.CheckConstraint("sort_order >= 0", name="ck_venue_images_sort_order"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_venue_images_venue_id", "venue_images", ["venue_id"], unique=False)
    op.create_index(
        "uq_one_cover_per_venue",
        "venue_images",
        ["venue_id"],
        unique=True,
        postgresql_where=sa.text("role = 'COVER'"),
    )
    op.create_table(
        "slots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pitch_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "LOCKED", "BOOKED", "CLOSED", name="slot_status"),
            nullable=False,
        ),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by_order_id", sa.UUID(), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("pitch_id"), "="),
            (sa.text("tstzrange(starts_at, ends_at, '[)')"), "&&"),
            using="gist",
            name="ex_slots_no_overlap",
        ),
        sa.CheckConstraint(
            "(status = 'LOCKED' AND locked_until IS NOT NULL "
            "AND locked_by_order_id IS NOT NULL) OR "
            "(status <> 'LOCKED' AND locked_until IS NULL "
            "AND locked_by_order_id IS NULL)",
            name="ck_slots_lock_fields",
        ),
        sa.CheckConstraint(
            "date(starts_at AT TIME ZONE 'Asia/Shanghai') = "
            "date((ends_at - INTERVAL '1 microsecond') "
            "AT TIME ZONE 'Asia/Shanghai')",
            name="ck_slots_same_local_day",
        ),
        sa.CheckConstraint("price_cents >= 0", name="ck_slots_price_cents"),
        sa.CheckConstraint("starts_at < ends_at", name="ck_slots_time_order"),
        sa.ForeignKeyConstraint(["pitch_id"], ["pitches.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pitch_id", "starts_at", "ends_at", name="uq_slots_pitch_time"),
    )
    op.create_index("ix_slots_pitch_id", "slots", ["pitch_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_slots_pitch_id", table_name="slots")
    op.drop_table("slots")
    op.drop_index(
        "uq_one_cover_per_venue",
        table_name="venue_images",
        postgresql_where=sa.text("role = 'COVER'"),
    )
    op.drop_index("ix_venue_images_venue_id", table_name="venue_images")
    op.drop_table("venue_images")
    op.drop_index("ix_venue_facilities_venue_id", table_name="venue_facilities")
    op.drop_table("venue_facilities")
    op.drop_index("ix_pitches_venue_id", table_name="pitches")
    op.drop_table("pitches")
    op.drop_index(
        "uq_one_active_primary_venue",
        table_name="venues",
        postgresql_where=sa.text("is_primary AND is_active"),
    )
    op.drop_table("venues")
    op.execute("DROP TYPE IF EXISTS slot_status")
    op.execute("DROP TYPE IF EXISTS image_role")
    op.execute("DROP TYPE IF EXISTS facility_code")
    op.execute("DROP TYPE IF EXISTS pitch_type")
    # ### end Alembic commands ###
